spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://database-1.c3e68syogmez.us-east-1.rds.amazonaws.com:5432/mydb
    username: postgres
    password: Hello_World_43
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10  # Adjust the pool size as needed
  jpa:
    hibernate:
      ddl-auto: update  # Can be 'none', 'validate', 'update', or 'create' based on your needs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true  # Set to 'false' to hide SQL in logs (optional)
    format-sql: true  # Optional: formats the SQL in logs (for readability)
  rabbitmq:
    host: b-22d8426a-5c46-4f06-a0be-fbe75bfb34e8.mq.us-east-1.amazonaws.com
    port: 5671
    username: admin
    password: Hello_World_43
    ssl:
      enabled: true
      algorithm: TLSv1.2
    virtual-host: /
server:
  port: 8081
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    enabled: true

ai-service:
  url: http://54.85.62.171:8000